#=================================================
#   Description: Build OpenWrt using GitHub Actions
#   Lisence: MIT
#   Author: P3TERX
#   Blog: https://p3terx.com
#   Modified: Basstorm
#=================================================

name: Build OpenWrt

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:

    - name: Checkout
      uses: actions/checkout@v1

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        #docker rmi `docker images -q`
        sudo -E swapoff /swapfile
        sudo -E rm -rf /swapfile /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo -E apt-get remove -y --purge azure-cli ghc zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php* mssql-tools msodbcsql17
        sudo -E apt-get update -y
        sudo -E apt-get full-upgrade -y
        sudo -E apt-get install -y build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-8 gcc++-8 gcc-8-multilib g++-8-multilib p7zip p7zip-full msmtp libssl-dev texinfo libreadline-dev libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint ccache curl wget vim nano python python3 python-pip python3-pip python-ply python3-ply haveged lrzsz device-tree-compiler
        sudo -E ln -sf /usr/bin/gcc-8 /usr/bin/gcc
        sudo -E ln -sf /usr/bin/g++-8 /usr/bin/g++
        sudo -E ln -sf /usr/bin/gcc-ar-8 /usr/bin/gcc-ar
        sudo -E ln -sf /usr/bin/gcc-nm-8 /usr/bin/gcc-nm
        sudo -E ln -sf /usr/bin/gcc-ranlib-8 /usr/bin/gcc-ranlib
        sudo -E apt-get autoremove -y --purge
        sudo -E apt-get clean -y
        sudo -E rm -rf /usr/share/dotnet /etc/mysql /etc/php

    - name: Clone source code
      env: 
        REPO_URL: https://github.com/project-openwrt/openwrt.git
        REPO_BRANCH: master
      run: git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt

    - name: Update feeds
      run: cd openwrt && ./scripts/feeds update -a

    - name: Install feeds
      run: cd openwrt && ./scripts/feeds install -a

    - name: Load custom configuration
      run: |
        [ -e files ] && mv files openwrt/files
        [ -e .config ] && mv .config openwrt
        cd openwrt
        make defconfig

    - name: Download package
      run: |
        cd openwrt && make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: Build
      run: |
        cd openwrt
        echo -e "$(nproc) thread build"
        make -j$(nproc) V=s

    - name : Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: OpenWrt-x86_64
        path: openwrt/bin

    - name: Organize files
      run: |
        cp openwrt/bin/targets/x86/64/openwrt-x86-64-combined-squashfs.img Basstorm-openwrt-x86-64-combined-squashfs.img
        sha256sum Basstorm* > sha256sums.txt
        cd openwrt/bin && zip -r $GITHUB_WORKSPACE/OpenWrt-x86_64.zip *

    - name: Upload to release
      uses: meeDamian/github-release@1.0
      with:
        token: ${{ secrets.OPENWRT_TOKEN }}
        gzip: false
        files: >
          OpenWrt-x86_64.zip
          sha256sums.txt
          Basstorm-openwrt-x86-64-combined-squashfs.img
        allow_override: true
